language: node_js
node_js:
  - "9"
dist: trusty
sudo: false
branches:
  only:
    - master

script:
  - npm cache clean --force
  - npm run build.prod
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master